In [1]:
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from PIL import Image
import os

In [2]:
img=cv2.imread('./image/1 (4).png')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thr = cv2.threshold(imgray, 127, 255, 0)
_, contours, _ = cv2.findContours(thr, cv2.RETR_TREE,
                                 cv2.CHAIN_APPROX_SIMPLE)

cv2.drawContours(img, contours, -1, (0, 0, 255), 1)
cv2.imshow('imgray', img)
cv2.imshow('thresh', thr)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img=cv2.imread('./image/1 (4).png', cv2.IMREAD_GRAYSCALE)
ret, bImage = cv2.threshold(img, 50, 250, cv2.THRESH_BINARY_INV)
print(bImage)
cv2.imshow('img', img)
cv2.imshow('bImage', bImage)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[250 250 250 ... 250 250 250]
 [250 250 250 ... 250 250 250]
 [250 250 250 ... 250 250 250]
 ...
 [250 250 250 ...   0   0   0]
 [250 250 250 ...   0   0   0]
 [250 250 250 ...   0   0   0]]


In [ ]:
kernel= cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(5,3))
#kernel = np.ones((5,5), np.uint8)
closing = cv2.morphologyEx(bImage, cv2.MORPH_OPEN,kernel,iterations = 3)
contours = cv2.findContours(closing, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[1]
rects = []
img_w = img.shape[1]
for i, cnt in enumerate(contours):
    x, y, w, h = cv2.boundingRect(cnt)
    print(x, y, w, h)
    #if h < 30: continue # 너무 작으면 생략하기
    #if w < 30: continue
    #if w > im_w / 5: continue # 너무 크면 생략하기
    #y2 = round(y / 10) * 10 # Y좌표 맞추기
    index = y
    rects.append((index, x, y, w, h))              #(index, x, y, w, h)) 

In [ ]:
    
rects = sorted(rects, key=lambda x:x[0]) # 정렬하기
img_result = []
img_for_class = img.copy()

margin_pixel = 10
margin_pixel1 = 0

for rect in rects:
    #[y:y+h, x:x+w]
    img_result.append(
        img_for_class[rect[2]-margin_pixel : rect[2]+rect[4]+margin_pixel, 
                      rect[1]-margin_pixel1 : rect[1]+rect[3]+margin_pixel1])
    
    # Draw the rectangles
    cv2.rectangle(img, (rect[1], rect[2]), 
                  (rect[1] + rect[3], rect[2] + rect[4]), (0, 255, 0), 0) 

In [ ]:
cv2.imshow('closing', closing)
cv2.imshow('img_for_class', cv2.imshow)
cv2.waitKey()
cv2.destroyAllWindows()